[package]
name = "carbon-footprint-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"]}
wiremock = "0.5"

[dev-dependencies]
toml