[package]
name = "carbon-footprint-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.5"
prettytable-rs = "0.10.0"
reqwest = "^0.11"
rpassword = "7.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"]}
wiremock = "0.5"